services:
  beszel-monitor:
    image: beszel-monitor
    container_name: beszel-monitor
    network_mode: host
    volumes:
      - ./data:/app/data
    environment:
      - GIN_MODE=release
      - DATABASE_PATH=/app/data/badger_data
      # - POCKETBASE_BASE_URL=${POCKETBASE_BASE_URL:-https://bz.baidua.top}
      # - POCKETBASE_EMAIL=${POCKETBASE_EMAIL}
      # - POCKETBASE_PASSWORD=${POCKETBASE_PASSWORD}
    restart: unless-stopped

# 注意：使用 network_mode: host 时，不再需要自定义 networks 和端口映射
