version: '3.8'

services:
  beszel-monitor:
    image: beszel-monitor
    container_name: beszel-monitor
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - GIN_MODE=release
      - DATABASE_PATH=/app/data/badger_data
      # - POCKETBASE_BASE_URL=${POCKETBASE_BASE_URL:-https://bz.baidua.top}
      # - POCKETBASE_EMAIL=${POCKETBASE_EMAIL}
      # - POCKETBASE_PASSWORD=${POCKETBASE_PASSWORD}
    restart: unless-stopped
    networks:
      - beszel-network

networks:
  beszel-network:
    driver: bridge

volumes:
  beszel-data:
    driver: local